log-level: WARN # ERROR, WARN, INFO, DEBUG
timeout: 10
showtime: 30
uptime:
  start:
    hour: 6
    minute: 30
  end: 
    hour: 22
    minute: 00
  sleepinterval: 120
show:
  - dwdalerts:
    name: "dwdalerts"
    vis-min-level: 3 # warning levels between 0 and 4
  - bkw:
    name: "bkw"
    uri: "http://192.168.50.80/rpc/Shelly.GetStatus"
  - pv:
    name: "pv"
    evcc-uri: "http://192.168.50.253:7070/api/state"
  - battery:
    name: "battery"
    evcc-uri: "http://192.168.50.253:7070/api/state"
  - em3:
    name: "em3"
    uri: "http://192.168.50.179/status"
  - wallbox:
    name: "wallbox"
    evcc-uri: "http://192.168.50.253:7070/api/state"
  - car:
    name: "car"
  - trash:
    name: "trash"
  - advent:
    name: "advent"
  - birthday:
    name: "birthday"
  - washing:
    name: "washing"
    dryer-uri: "http://192.168.50.192/rpc/Shelly.GetStatus"
    wash-uri: "http://192.168.50.2/rpc/Shelly.GetStatus"
    power-off-threshold: 1    # Watts
    idle-threshold: 10        # Watts
  - sunset:
    name: "sunset"
  # - forecast:
  #   name: "forecast"
  - clock:
    name: "clock"

ulanzi:
  uri: http://192.168.50.131/api/screen
  info: http://192.168.50.131/api/matrixinfo
