log-level: DEBUG # WARNING, DEBUG
timeout: 10
showtime: 30
uptime:
  start:
    hour: 6
    minute: 30
  end: 
    hour: 22
    minute: 00
  sleepinterval: 120
show:
  - bkw:
    name: "bkw"
    uri: "http://192.168.50.80/rpc/Shelly.GetStatus"
  - pv:
    name: "pv"
  - battery:
    name: "battery"
  - em3:
    name: "em3"
    uri: "http://192.168.50.179/status"
# - wallbox:
#   name: "wallbox"
# - car:
#   name: "car"
  - trash:
    name: "trash"
  - advent:
    name: "advent"
  - birthday:
    name: "birthday"
    evcc-uri: "http://192.168.50.215:7070/api/state"
  - washing:
    name: "washing"
    dryer-uri: "http://192.168.50.192/rpc/Shelly.GetStatus"
    wash-uri: "http://192.168.50.2/rpc/Shelly.GetStatus"
    power-off-threshold: 1    # Watts
    idle-threshold: 10        # Watts
  - clock:
    name: "clock"
ulanzi:
  uri: http://192.168.50.131/api/screen
  info: http://192.168.50.131/api/matrixinfo
pv:
  host: "192.168.50.196"
  port: 502
  slave_id: 1