log-level: DEBUG # WARNING, DEBUG
timeout: 10
showtime: 30
uptime:
  start:
    hour: 6
    minute: 0
  end: 
    hour: 22
    minute: 0
  sleepinterval: 120
show:
  - washing:
    name: "washing"
    dryer-uri: "http://192.168.50.192/rpc/Shelly.GetStatus"
    wash-uri: "http://192.168.50.2/rpc/Shelly.GetStatus"
    power-off-threshold: 1    # Watts
    idle-threshold: 10        # Watts
  - bkw:
    name: "bkw"
    uri: "http://192.168.50.80/rpc/Shelly.GetStatus"
  - em3:
    name: "em3"
    uri: "http://192.168.50.179/status"
  - trash:
    name: "trash"
  - advent:
    name: "advent"
  - birthday:
    name: "birthday"
  - clock:
    name: "clock"
ulanzi:
  uri: http://192.168.50.131/api/screen
  info: http://192.168.50.131/api/matrixinfo